"""current Revision

Revision ID: 1c187db2b291
Revises: d40d8992df09
Create Date: 2022-12-12 11:07:27.086413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c187db2b291'
down_revision = 'd40d8992df09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
