"""current Revision

Revision ID: 8326c9da55cc
Revises: 1c187db2b291
Create Date: 2022-12-12 11:08:38.005068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8326c9da55cc'
down_revision = '1c187db2b291'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'comp_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'comp_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
